# Import modules
from tfne.encodings.codeepneat.modules.codeepneat_module_association import MODULES
from tfne.encodings.codeepneat.modules.codeepneat_module_base import CoDeepNEATModuleBase
from tfne.encodings.codeepneat.modules.codeepneat_module_conv2d import CoDeepNEATModuleConv2D
from tfne.encodings.codeepneat.modules.codeepneat_module_densedropout import CoDeepNEATModuleDenseDropout
from tfne.encodings.codeepneat.modules.codeepneat_module_dropout import CoDeepNEATModuleDropout
from tfne.encodings.codeepneat.modules.codeepneat_module_activation import CoDeepNEATModuleActivation
